name: Feature Request
description: Propose a new feature or improvement for GateBridge Core.
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Have an idea to improve GateBridge Core? We would love to hear it!
  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem or limitation? Describe it.
      placeholder: I am frustrated when...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you would like to see implemented.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false
